// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameEvent } from "./GameEvent";

/**
 * The result of successfully applying an action.
 */
export type ActionResult = { events: Array<GameEvent>, };
