// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CombatSubPhase } from "./CombatSubPhase";
import type { Power } from "./Power";
import type { RegionId } from "./RegionId";

/**
 * Tracks the state of an active battle.
 */
export type ActiveCombat = { 
/**
 * Location where the battle takes place.
 */
location: RegionId, 
/**
 * The attacking power.
 */
attacker: Power, 
/**
 * Units fighting for the attacker (by ID).
 */
attacker_units: Array<number>, 
/**
 * Units fighting for the defender.
 */
defender_units: Array<number>, 
/**
 * The defending power (primary).
 */
defender: Power, 
/**
 * Current round number (starts at 1).
 */
round: number, 
/**
 * Current sub-phase within this combat round.
 */
sub_phase: CombatSubPhase, 
/**
 * Hits pending allocation to the defender.
 */
pending_attacker_hits: number, 
/**
 * Hits pending allocation to the attacker.
 */
pending_defender_hits: number, 
/**
 * Whether this is an amphibious assault.
 */
is_amphibious: boolean, 
/**
 * Units eligible for shore bombardment (by ID).
 */
bombardment_units: Array<number>, 
/**
 * Dice results from the last roll (for UI display).
 */
last_roll: Array<number>, 
/**
 * Regions the attacker can retreat to.
 */
retreat_options: Array<RegionId>, 
/**
 * Whether enemy has a destroyer (cancels sub abilities).
 */
enemy_has_destroyer: boolean, 
/**
 * Units that have been submerged this battle.
 */
submerged_units: Array<number>, };
