// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Power } from "./Power";
import type { RegionId } from "./RegionId";
import type { UnitType } from "./UnitType";

/**
 * All possible player actions. Every interaction with the engine is an Action.
 */
export type Action = { "PurchaseUnit": { unit_type: UnitType, count: number, } } | { "RemovePurchase": { unit_type: UnitType, count: number, } } | { "RepairFacility": { territory_id: number, damage_to_repair: number, } } | "ConfirmPurchases" | { "MoveUnit": { unit_id: number, path: Array<RegionId>, } } | { "UndoMove": { unit_id: number, } } | "ConfirmCombatMovement" | { "SelectBattle": { location: RegionId, } } | "RollAttack" | "RollDefense" | { "SelectCasualties": { casualties: Array<number>, } } | { "AttackerRetreat": { to: RegionId, } } | { "SubmergeSubmarine": { unit_id: number, } } | "ContinueCombatRound" | { "MoveUnitNonCombat": { unit_id: number, path: Array<RegionId>, } } | { "LandAirUnit": { unit_id: number, territory_id: RegionId, } } | "ConfirmNonCombatMovement" | { "PlaceUnit": { unit_type: UnitType, territory_id: number, } } | "ConfirmMobilization" | "ConfirmIncome" | { "DeclareWar": { against: Power, } } | "Undo" | "ConfirmPhase";
