// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State for the Collect Income phase.
 */
export type CollectIncomeState = { base_income: number, objective_bonus: number, convoy_losses: number, total_collected: number, };
