// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sub-phase within a single battle.
 */
export type CombatSubPhase = "AAFire" | "AAFireCasualties" | "ShoreBombardment" | "ShoreBombardmentCasualties" | "AttackerSubmarineStrike" | "DefenderSubmarineStrikeCasualties" | "DefenderSubmarineStrike" | "AttackerSubmarineStrikeCasualties" | "AttackerRolls" | "DefenderRolls" | "DefenderSelectsCasualties" | "AttackerSelectsCasualties" | "AttackerDecision" | "BattleOver";
