// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionId } from "./RegionId";

/**
 * State for the Conduct Combat phase.
 */
export type CombatState = { pending_battles: Array<RegionId>, resolved_battles: Array<RegionId>, current_battle: RegionId | null, };
