// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All possible errors from the game engine.
 */
export type EngineError = { "NotYourTurn": { current: string, } } | { "WrongPhase": { expected: string, actual: string, } } | { "InsufficientIPCs": { needed: number, available: number, } } | { "IllegalMove": { reason: string, } } | { "InvalidAction": { reason: string, } } | { "UnitNotFound": { unit_id: number, } } | { "TerritoryNotFound": { territory_id: number, } } | { "CannotUndo": { reason: string, } } | { "Serialization": string } | { "Deserialization": string } | { "SetupError": string } | { "Internal": string };
