// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacilityType } from "./FacilityType";

/**
 * A facility in a territory.
 */
export type Facility = { facility_type: FacilityType, damage: number, max_damage: number, operational: boolean, };
