// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Facility types that can exist in land territories.
 */
export type FacilityType = "MinorIndustrialComplex" | "MajorIndustrialComplex" | "AirBase" | "NavalBase";
