// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";
import type { Power } from "./Power";
import type { RegionId } from "./RegionId";
import type { Team } from "./Team";
import type { UnitType } from "./UnitType";

/**
 * Narrative events for the event log and UI feedback.
 */
export type GameEvent = { "PhaseChanged": { from: Phase, to: Phase, } } | { "TurnChanged": { power: Power, turn: number, } } | { "WarDeclared": { aggressor: Power, target: Power, } } | { "BattleStarted": { location: RegionId, } } | { "BattleEnded": { location: RegionId, attacker_won: boolean, } } | { "CapitalCaptured": { territory_id: number, by: Power, } } | { "TerritoryLiberated": { territory_id: number, to: Power, } } | { "ConvoyDisrupted": { zone: number, power: Power, lost_ipcs: number, } } | { "VictoryAchieved": { winner: Team, } } | { "UnitsPurchased": { unit_type: UnitType, count: number, cost: number, } } | { "UnitsPlaced": { unit_type: UnitType, territory_id: number, } } | { "IncomeCollected": { power: Power, amount: number, } };
