// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";
import type { PhaseState } from "./PhaseState";
import type { PoliticalState } from "./PoliticalState";
import type { Power } from "./Power";
import type { PowerState } from "./PowerState";
import type { SeaZoneState } from "./SeaZoneState";
import type { TerritoryState } from "./TerritoryState";

/**
 * The complete game state. This is the single source of truth.
 */
export type GameState = { turn_number: number, current_power: Power, current_phase: Phase, phase_state: PhaseState, territories: Array<TerritoryState>, sea_zones: Array<SeaZoneState>, powers: Array<PowerState>, political: PoliticalState, rng_seed: bigint, rng_counter: bigint, };
