// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

/**
 * A legal action with a human-readable description.
 */
export type LegalAction = { action: Action, description: string, };
