// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitType } from "./UnitType";

/**
 * State for the Mobilize phase.
 */
export type MobilizeState = { placements: Array<[UnitType, number]>, units_to_place: Array<[UnitType, number]>, };
