// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedMove } from "./PlannedMove";

/**
 * State for the Non-Combat Movement phase.
 */
export type NonCombatMoveState = { moves: Array<PlannedMove>, };
