// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectIncomeState } from "./CollectIncomeState";
import type { CombatMoveState } from "./CombatMoveState";
import type { CombatState } from "./CombatState";
import type { MobilizeState } from "./MobilizeState";
import type { NonCombatMoveState } from "./NonCombatMoveState";
import type { PurchaseState } from "./PurchaseState";

/**
 * Per-phase sub-state. Tracks what has been done in the current phase.
 */
export type PhaseState = { "Purchase": PurchaseState } | { "CombatMove": CombatMoveState } | { "Combat": CombatState } | { "NonCombatMove": NonCombatMoveState } | { "Mobilize": MobilizeState } | { "CollectIncome": CollectIncomeState };
