// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionId } from "./RegionId";

/**
 * A planned unit move during combat movement.
 */
export type PlannedMove = { unit_id: number, path: Array<RegionId>, from: RegionId, to: RegionId, };
