// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoliticalTriggers } from "./PoliticalTriggers";

/**
 * Political state tracking wars, triggers, and neutrals.
 */
export type PoliticalState = { 
/**
 * war_matrix[a][b] == true means power a is at war with power b
 */
war_matrix: [[boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean]], triggers: PoliticalTriggers, };
