// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Political triggers that affect gameplay.
 */
export type PoliticalTriggers = { us_at_war: boolean, us_war_turn: number | null, soviet_at_war_with_axis: boolean, japan_attacked_uk_anzac: boolean, london_captured: boolean, paris_captured: boolean, };
