// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The nine playable powers in Global 1940 2nd Edition.
 */
export type Power = "Germany" | "SovietUnion" | "Japan" | "UnitedStates" | "China" | "UnitedKingdom" | "Italy" | "ANZAC" | "France";
