// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Power } from "./Power";

/**
 * Per-power mutable state.
 */
export type PowerState = { power: Power, ipcs: number, ipcs_europe: number, ipcs_pacific: number, at_war: boolean, capital_captured: boolean, researched_techs: Array<string>, };
