// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitType } from "./UnitType";

/**
 * State for the Purchase & Repair phase.
 */
export type PurchaseState = { purchases: Array<[UnitType, number]>, repairs: Array<[number, number]>, ipcs_spent: number, };
