// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A region is either a land territory or a sea zone.
 */
export type RegionId = { "Land": number } | { "Sea": number };
