// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitInstance } from "./UnitInstance";

/**
 * Mutable state of a sea zone during a game.
 */
export type SeaZoneState = { units: Array<UnitInstance>, };
