// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of a territory (affects political rules).
 */
export type TerritoryType = "Normal" | "ProAxis" | "ProAllies" | "TrueNeutral" | "Impassable";
