// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Facility } from "./Facility";
import type { Power } from "./Power";
import type { UnitInstance } from "./UnitInstance";

/**
 * Mutable state of a land territory during a game.
 */
export type TerritoryState = { owner: Power | null, units: Array<UnitInstance>, facilities: Array<Facility>, just_captured: boolean, };
