// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The domain a unit operates in.
 */
export type UnitDomain = "Land" | "Air" | "Sea";
