// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All unit types in Global 1940 2nd Edition.
 */
export type UnitType = "Infantry" | "MechInfantry" | "Artillery" | "Tank" | "AAA" | "Fighter" | "TacticalBomber" | "StrategicBomber" | "Transport" | "Submarine" | "Destroyer" | "Cruiser" | "Carrier" | "Battleship";
