// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Power } from "./Power";
import type { UnitType } from "./UnitType";

/**
 * A specific unit on the board.
 */
export type UnitInstance = { id: number, unit_type: UnitType, owner: Power, hits_taken: number, moved_this_turn: boolean, movement_remaining: number, cargo: Array<number>, };
